/*
 * license header, select License Headers in Project Properties.
 */
package StaffdatabaseMySQL;



import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JTable;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;


/**
 *
 * @author Mose
 */
public class StaffdatabaseMySQL extends javax.swing.JFrame {
 
    
    private static final String username="root";
    private static final String password="1279";
    private static final String dataConn="jdbc:mysql://localhost:3306/staffdata";
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
      int q, i;       
    
    /**
     * Creates new form StaffdatabaseMySQL
     */
    public StaffdatabaseMySQL() {
        initComponents();
        updateDB();
        
    }

    /**
     * Method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. 
     * The content of this method is always regenerated by the Form Editor.
     */
    
   
    @SuppressWarnings("unchecked")
    public void updateDB()
    {
        
         try
        {
           
           Class.forName("com.mysql.cj.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);
            pst = sqlConn.prepareStatement("select * from staffdata");
            
            rs =pst.executeQuery();
            ResultSetMetaData StData = rs.getMetaData();
            
            q = StData.getColumnCount();
            
            DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
            RecordTable.setRowCount(0);
            
            while(rs.next()){
                
                Vector columnData = new Vector();
                
                for (i = 1; i <= q; i++)
                {
                    
                    columnData.add(rs.getString("staffid"));
                    columnData.add(rs.getString("firstname"));
                    columnData.add(rs.getString("surname"));
                    columnData.add(rs.getString("studyqualifications"));
                    columnData.add(rs.getString("address"));
                    columnData.add(rs.getString("email"));
                    columnData.add(rs.getString("gender"));
                    columnData.add(rs.getString("telephone"));
                    columnData.add(rs.getString("strikes"));
                    columnData.add(rs.getString("everawarded"));
                    columnData.add(rs.getString("sickleave"));
                    columnData.add(rs.getString("studyleave"));
                    
                }
                    RecordTable.addRow(columnData);                
                
            }
         
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cbogender = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtstaffid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsurname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txttelephone = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        cbostudyleave = new javax.swing.JComboBox<>();
        cboStudyLeave = new javax.swing.JLabel();
        cboSickLeave = new javax.swing.JLabel();
        cbosickleave = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        cboStriked = new javax.swing.JLabel();
        cbostrikes = new javax.swing.JComboBox<>();
        cboAwarded = new javax.swing.JLabel();
        cboeverawarded = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtstudyqualifications = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnAddNew = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setText("Staff-info Management Database system");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1370, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1410, 130));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbogender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "Male", "Female" }));
        jPanel3.add(cbogender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 100, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, -1));

        txtstaffid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtstaffid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstaffidActionPerformed(evt);
            }
        });
        jPanel3.add(txtstaffid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 360, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Surname");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, -1));

        txtsurname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtsurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 360, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Address");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 360, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Telephone");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 100, 40));

        txttelephone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txttelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 160, 40));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 140));

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 140));

        jPanel6.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 140));

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 140));

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 140));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 140));

        jPanel6.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, 140));

        cbostudyleave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbostudyleave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jPanel6.add(cbostudyleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, 30));

        cboStudyLeave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboStudyLeave.setText("Study Leave");
        jPanel6.add(cboStudyLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        cboSickLeave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboSickLeave.setText("Sick Leave");
        jPanel6.add(cboSickLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, -1));

        cbosickleave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbosickleave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jPanel6.add(cbosickleave, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 230, 120));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 220, -1));

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 140));

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 140));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 140));

        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 140));

        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 230, 140));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 230, 140));

        jPanel15.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, 140));

        cboStriked.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboStriked.setText("Striked");
        jPanel15.add(cboStriked, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        cbostrikes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbostrikes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jPanel15.add(cbostrikes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 30));

        cboAwarded.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboAwarded.setText("Awarded");
        jPanel15.add(cboAwarded, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 30));

        cboeverawarded.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboeverawarded.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jPanel15.add(cboeverawarded, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, 30));

        jPanel3.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 230, 120));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Staff ID");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Gender");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 90, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Study Qualifications");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 70));

        txtstudyqualifications.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtstudyqualifications.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel3.add(txtstudyqualifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 300, 70));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 360, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Email");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 60, 50));

        txtfirstname.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 360, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 520, 510));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "staffid", "firstname", "surname", "studyqualifications", "address", "email", "gender", "telephone", "strikes", "everawarded", "sickleave", "studyleave"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 480));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 850, 500));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddNew.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnAddNew.setText("Add New");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });
        jPanel5.add(btnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 70));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel5.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 180, 70));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 180, 70));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel5.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 180, 70));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 180, 70));

        btnImport.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        jPanel5.add(btnImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 180, 70));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel5.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 180, 70));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 1380, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 1410, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private JFrame frame; 
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       frame= new JFrame("Exit");
       if (JOptionPane.showConfirmDialog (frame, "Sure to exit?","Staff Management System",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
           System.exit(0);
       }// TODO add handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
  
       
       try 
       {
       Class.forName("com.mysql.cj.jdbc.Driver");
               sqlConn = DriverManager.getConnection(dataConn, username, password);
               pst = sqlConn.prepareStatement("insert into staffdata (staffid, firstname, surname, studyqualifications,address, email,"
                       + " telephone, gender, strikes, everawarded, sickleave, studyleave)value(?,?,?,?,?,?,?,?,?,?,?,?)");
               pst.setString(1, txtstaffid.getText());
               pst.setString(2, txtfirstname.getText());
               pst.setString(3, txtsurname.getText());
               pst.setString(4, txtstudyqualifications.getText());
               pst.setString(5, txtaddress.getText());
               pst.setString(6, txtemail.getText());
               pst.setString(8, (String) cbogender.getSelectedItem());
               pst.setString(7, txttelephone.getText());
               pst.setString(9, (String)cbostrikes.getSelectedItem());
               pst.setString(10, (String)cboeverawarded.getSelectedItem());
               pst.setString(11, (String)cbosickleave.getSelectedItem());
               pst.setString(12, (String)cbostudyleave.getSelectedItem());
               
               pst.executeUpdate ();
                JOptionPane.showMessageDialog(this, "staff info updated");
                updateDB();
       }
         
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffdatabaseMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(StaffdatabaseMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
         MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        } 
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO added handling code here:
        
         DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try
        {
           int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
           
           int deleteItem = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete item",
                   "Warning",JOptionPane.YES_NO_OPTION);
             if (deleteItem ==JOptionPane.YES_OPTION ) 
             {                 
         
           Class.forName("com.mysql.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);
                pst = sqlConn.prepareStatement("delete from StaffdatabaseMySQL where id =?");
                
               pst.setInt(1, id);
               pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Selected staff Record deleted");
              updateDB();
            
            
            txtstaffid.setText("");
            txtfirstname.setText("");
            txtsurname.setText("");
            txtstudyqualifications.setText("");
            txtaddress.setText("");
            cbogender.setSelectedIndex(0);
            txttelephone.setText("");
            cbostrikes.setSelectedIndex(0);
            cboeverawarded.setSelectedIndex(0);
            cbosickleave.setSelectedIndex(0);
            cbostudyleave.setSelectedIndex(0);
            }
           
        }
        
        catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(StaffdatabaseMySQL.class.getName()).log(java.util.logging.Level.SEVERE, 
           null, ex);
        } catch (SQLException ex) {
             System.err.println(ex);

        } 
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO added handling code here:
         txtstaffid.setText("");
            txtfirstname.setText("");
            txtsurname.setText("");
            txtstudyqualifications.setText("");
            txtaddress.setText("");
            txtemail.setText("");
            cbogender.setSelectedIndex(0);
            txttelephone.setText("");
            cbostrikes.setSelectedIndex(0);
            cboeverawarded.setSelectedIndex(0);
            cbosickleave.setSelectedIndex(0);
            cbostudyleave.setSelectedIndex(0);
            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO added handling code here:
         DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        try
        {
           int id = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
         
           Class.forName("com.mysql.jdbc.Driver"); 
            sqlConn = DriverManager.getConnection(dataConn,username,password);
                pst = sqlConn.prepareStatement("update staffdata set staffid =?,firstname=?,surname=?,"
                + "address=?,gender=?,telephone=?,strikes=?,everawarded=?,studyleave=?,sickleave=?, where id =?");
            
            pst.setString(1, txtstaffid.getText());
            pst.setString(2, txtfirstname.getText());
            pst.setString(3, txtsurname.getText());
            pst.setString(3, txtstudyqualifications.getText());
            pst.setString(4, txtaddress.getText());
            pst.setString(5, (String) cbogender.getSelectedItem());
            pst.setString(6, txttelephone.getText());
            pst.setString(7, (String)cbostrikes.getSelectedItem());
            pst.setString(8, (String)cboeverawarded.getSelectedItem());
            pst.setString(9, (String)cbosickleave.getSelectedItem());
            pst.setString(10, (String)cbostudyleave.getSelectedItem());
            pst.setInt(15, id);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Staff Record updated");
            updateDB();
          
        }
        
        catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(StaffdatabaseMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
             System.err.println(ex);

        } 
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        txtstaffid.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        txtfirstname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        txtsurname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        txtstudyqualifications.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        txtaddress.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        txtemail.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
        cbogender.setSelectedItem(RecordTable.getValueAt(SelectedRows, 7).toString());        
        txttelephone.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
        cbostrikes.setSelectedItem(RecordTable.getValueAt(SelectedRows, 9).toString());
        cboeverawarded.setSelectedItem(RecordTable.getValueAt(SelectedRows, 10).toString());
        cbosickleave.setSelectedItem(RecordTable.getValueAt(SelectedRows, 11).toString());
        cbostudyleave.setSelectedItem(RecordTable.getValueAt(SelectedRows, 12).toString());
        
    }//GEN-LAST:event_btnImportActionPerformed

    private void txtstaffidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstaffidActionPerformed
        // TODO added  handling code here:
    }//GEN-LAST:event_txtstaffidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffdatabaseMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffdatabaseMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffdatabaseMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffdatabaseMySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffdatabaseMySQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel cboAwarded;
    private javax.swing.JLabel cboSickLeave;
    private javax.swing.JLabel cboStriked;
    private javax.swing.JLabel cboStudyLeave;
    private javax.swing.JComboBox<String> cboeverawarded;
    private javax.swing.JComboBox<String> cbogender;
    private javax.swing.JComboBox<String> cbosickleave;
    private javax.swing.JComboBox<String> cbostrikes;
    private javax.swing.JComboBox<String> cbostudyleave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtstaffid;
    private javax.swing.JTextField txtstudyqualifications;
    private javax.swing.JTextField txtsurname;
    private javax.swing.JTextField txttelephone;
    // End of variables declaration//GEN-END:variables
}
